### ISSUE TITLE
Plan to add ngram_range argument for CountVectorizer()?

### ISSUE THREAD

**Issue by jaeyk** [saraswatmks/superml#15]
Hi. First of all, this is a great idea. I build ML models for text analysis both in R and Python. It has been a headache to translate Python code in R. This package is a great help. I looked up the CountVectorizer() function and I was wondering whether you plan to add ngram_range argument to it. Thanks.

**Comment by saraswatmks** [comment]
Hi @jaeyk Thanks for the kind appreciation. I stopped developing this project because of priorities. But given that it can help you, I will add the argument soon, give me few days:)

**Comment by saraswatmks** [comment]
`ngram_range` feature is now available with CountVectorizer and TfidfVectorizer in superml #16. To use it, either you can do install from github directly or wait for a couple of days for the updated package to be published on cran. Happy coding:)

**Comment by jaeyk** [comment]
@saraswatmks  Thanks for incorporating my feedback! Happy coding!
