### ISSUE TITLE
transform doesn't do anything with supplied arguments?

### ISSUE THREAD

**Issue by rowrowrowyourboat** [saraswatmks/superml#21]
Running  [this example in from the tutorial](https://saraswatmks.github.io/superml/articles/Guide-to-TfidfVectorizer.html)
 as shown below, it looks like TfIdfVectorizer$transform() doesn't do anything with the supplied arguements since both` train_tf_features `and `test_tf_features` are identical or this isn't a great example since there's no difference in the output.

Here's the example from the tutorial along with my additional code showing that they are identical.

```
library(data.table)
library(superml)

# use sents from above
sents <-  c('i am going home and home',
            'where are you going.? //// ',
            'how does it work',
            'transform your work and go work again',
            'home is where you go from to work',
            'how does it work')

# create dummy data
train <- data.table(text = sents, target = rep(c(0,1), 3))
test <- data.table(text = sample(sents), target = rep(c(0,1), 3))

# initialise the class, set parallel to TRUE for fast computation
tfv <- TfIdfVectorizer$new(min_df = 0.3, remove_stopwords = FALSE, ngram_range = c(1,3), parallel = FALSE)

# we fit on train data
tfv$fit(train$text)

train_tf_features <- tfv$transform(train$text)
test_tf_features <- tfv$transform(test$text)

#WTF, they're the same
identical(train_tf_features, test_tf_features)
```

**Comment by saraswatmks** [comment]
thanks @rowrowrowyourboat for highlighting it. It's a bug and also the example doesn't show the impact of transform. Here's how it looks after fixing it bug (new version should be on cran in a couple of days):

#### Sample data
> tr = c('I am good', 'how are you doing')
> te = c('good bye see you', 'paris is in france')

#### TfidfVectorizer
> tfv = TfIdfVectorizer$new(remove_stopwords = F, parallel = F,)

> tfv$fit(tr)

> tfv$transform(tr)
            am are doing      good how i you
[1,] 0.7071068 0.0   0.0 0.7071068 0.0 0 0.0
[2,] 0.0000000 0.5   0.5 0.0000000 0.5 0 0.5

> tfv$transform(te)
     am are doing      good how i       you
[1,]  0   0     0 0.7071068   0 0 0.7071068
[2,]  0   0     0 0.0000000   0 0 0.0000000

#### CountVectorizer
> cv = CountVectorizer$new(remove_stopwords = F, parallel = F)

> cv$fit(tr)

> cv$transform(tr)
     am are doing good how i you
[1,]  1   0     0    1   0 0   0
[2,]  0   1     1    0   1 0   1

> cv$transform(te)
     am are doing good how i you
[1,]  0   0     0    1   0 0   1
[2,]  0   0     0    0   0 0   0
`
