### ISSUE TITLE
cannot find SVMTrainer

### ISSUE THREAD

**Issue by zhengkd95** [saraswatmks/superml#33]
Hi @saraswatmks , thank you for the smooth package. 
I noticed that the SVMTrainer is no longer in the R folder. Do you remove it for certain purpose?

Thank you!

**Comment by saraswatmks** [comment]
Hi @zhengkd95 I removed it due to dependency issues. But, will add it in the next version in few days. Unfortunately, I released the latest version to CRAN yesterday now I guess I need to wait for a month for the next release. Thanks for your cooperation.

**Comment by zhengkd95** [comment]
Thank you for the timely reply. Good to hear that.
